# Dockerfile.dev
ARG ELIXIR_VERSION=1.17.3
ARG OTP_VERSION=27.1.1
ARG DEBIAN_VERSION=bullseye-20240926-slim

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE}

RUN apt-get update -y && apt-get install -y build-essential git postgresql-client \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

ENV PATH="/usr/lib/postgresql/14/bin:${PATH}"

WORKDIR /app

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config/config.exs config/
COPY config/dev.exs config/
COPY config/test.exs config/

RUN mix deps.get 

RUN mkdir -p /app/.mix 
RUN mkdir -p /app/_build

COPY docker-entrypoint-dev.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint-dev.sh

ENV HOME /app

RUN chown -R nobody /app

ENTRYPOINT ["/usr/local/bin/docker-entrypoint-dev.sh"]
CMD [""]